/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("(C) 1998, 1999, 2000 Alex Roberts and Evan Lawrence");
gchar *s = N_("gedit is a small and lightweight text editor for GNOME.");
