/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Plugins manager...");
gchar *s = N_("Select the plugins to install:");
gchar *s = N_("_Select all");
gchar *s = N_("_Remove all");
gchar *s = N_("_Description");
gchar *s = N_("File name:");
gchar *s = N_("Author(s):");
gchar *s = N_("De_tails");
