/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Appearance");
gchar *s = N_("Show Statusbar");
gchar *s = N_("Show splitscreen");
gchar *s = N_("Display text on toolbar buttons");
gchar *s = N_("Editor Behavior");
gchar *s = N_("Enable Auto-indent");
gchar *s = N_("General");
gchar *s = N_("MDI (Multiple Document Interface)");
gchar *s = N_("Left\n"
              "Right\n"
              "Top\n"
              "Bottom\n"
              "");
gchar *s = N_("Notebook\n"
              "Toplevel\n"
              "Modal\n"
              "Default\n"
              "");
gchar *s = N_("Mode: ");
gchar *s = N_("Notebook Tab Position: ");
gchar *s = N_("Undo");
gchar *s = N_("Set limit on undo levels to :");
gchar *s = N_("level(s)");
gchar *s = N_("Documents");
gchar *s = N_("Fonts");
gchar *s = N_("Pick a Font");
gchar *s = N_("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz");
gchar *s = N_("Default Font: ");
gchar *s = N_("Colors");
gchar *s = N_("Pick a color");
gchar *s = N_("Pick a color");
gchar *s = N_("Background: ");
gchar *s = N_("Foreground: ");
gchar *s = N_("Fonts/Colors");
gchar *s = N_("Printing");
gchar *s = N_("Add _header");
gchar *s = N_("Enable word _wrapping");
gchar *s = N_("Print _line numbers every:");
gchar *s = N_("line(s)");
gchar *s = N_("_Portrait");
gchar *s = N_("_Landscape");
gchar *s = N_("Printing");
gchar *s = N_("Paper");
