/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Find");
gchar *s = N_("Find");
gchar *s = N_("Cursor\n"
              "Beginning of Document\n"
              "End of Document\n"
              "");
gchar *s = N_("Search for: ");
gchar *s = N_("Search from: ");
gchar *s = N_("Case sensitive");
gchar *s = N_("Reverse search");
