.TH GEDIT l "13 May 1998"
.SH NAME
\fBgEdit\fP \- GTK+ based text editor
.SH SYNTAX
.B gedit
.RI [ --help ]
.RI [ --version ]
.RI [ filename ]
.RI [ filename ]
.RI [ filename ]
.RI etc...
.SH DESCRIPTION
.B gEdit
is a text editor for the X Window System which uses the GTK+ widget set. It currently
supports creation, openning, closing, and saving of multiple files, search and replace,
an options interface, and loading of files via the command line. 
.LP
.SH OPTIONS
This is pretty straightforward.
.TP
.B \-\-help
.PD
Prints the command line options.
.TP
.B \-\-version
.PD
Prints the version of gEdit that you're using.
.TP
.B filename
.PD
Specifies the file to open when gEdit starts - if this is not specified, gEdit will
load a blank file with an Untitled label.
.SH BUGS
See the KNOWNBUGS file for a list of the bugs we know about but haven't bothered to
fix yet, if you find a bug that isn't listed in that file, email us.

.SH AUTHORS
Alex Roberts (bse@dial.pipex.com)
.TP
Evan Lawrence (evan@worldpath.net)
