/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("gedit: Number Converter plugin");
gchar *s = N_("_Value to be converted:");
gchar *s = N_("_Converted value:");
gchar *s = N_(" Decimal to _Hex ");
gchar *s = N_(" Decimal to _Octal ");
gchar *s = N_(" Hex to Decima_l ");
