/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Number Converter");
gchar *s = N_("Converted Value:");
gchar *s = N_("Value to be converted:");
gchar *s = N_("Decimal to Hex");
gchar *s = N_("Decimal to Octal");
gchar *s = N_("Hex to Decimal");
