/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Plugins manager...");
gchar *s = N_("Select the plugins to activate:");
gchar *s = N_("_Activate all");
gchar *s = N_("_Deactivate all");
gchar *s = N_("De_scription");
gchar *s = N_("File name:");
gchar *s = N_("Author(s):");
gchar *s = N_("De_tails");
