/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("gedit Plugin Manager");
gchar *s = N_("Select the plugins to install");
gchar *s = N_("Available Plugins");
gchar *s = N_("Available Plugins");
gchar *s = N_("Add >");
gchar *s = N_("< Remove");
gchar *s = N_("Add All >>");
gchar *s = N_("<< Remove All");
gchar *s = N_("Installed Plugins");
gchar *s = N_("Installed Plugins");
gchar *s = N_("Plugin description");
