/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("gedit: Set program location...");
gchar *s = N_("label");
gchar *s = N_("_Location to search for :");
gchar *s = N_("gedit: Browse for program location...");
