/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Replace");
gchar *s = N_("Find Next");
gchar *s = N_("Replace");
gchar *s = N_("Replace All");
gchar *s = N_("Search for: ");
gchar *s = N_("Replace with: ");
gchar *s = N_("beginning of document");
gchar *s = N_("cursor position");
gchar *s = N_("Case sensitive");
