/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Replace");
gchar *s = N_("Find");
gchar *s = N_("Replace");
gchar *s = N_("Replace All");
gchar *s = N_("_Search for: ");
gchar *s = N_("_Replace with: ");
gchar *s = N_("b_eginning of document");
gchar *s = N_("_cursor position");
gchar *s = N_("Case se_nsitive");
