/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("gedit: ASCII table");
gchar *s = N_("Insert char");
gchar *s = N_("If you wish to insert any of the characters in to the active \n"
              "document, select the character and click the \"Insert Char\" \n"
              "button or double click the character in the table.");
gchar *s = N_("Char");
gchar *s = N_("Dec#");
gchar *s = N_("Hex#");
gchar *s = N_("Name");
