/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("gedit: Document Info plugin");
gchar *s = N_("Update");
gchar *s = N_("File Name");
gchar *s = N_("Words");
gchar *s = N_("Paragraphs");
gchar *s = N_("Characters (with spaces)");
gchar *s = N_("Characters (no spaces)");
gchar *s = N_("Lines");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("Current line");
gchar *s = N_("Current column");
gchar *s = N_("0");
gchar *s = N_("0");
