/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("gedit: Sort plugin");
gchar *s = N_("Sort starting at column:");
gchar *s = N_("1");
gchar *s = N_("Case Sensitive");
