/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Choose the files to diff");
gchar *s = N_("From document");
gchar *s = N_("From document");
gchar *s = N_("From a file on disk");
gchar *s = N_("From a file on disk");
gchar *s = N_("don't translate this\n"
              "");
gchar *s = N_("don't translate this\n"
              "");
gchar *s = N_("diff found at : ");
gchar *s = N_("location");
gchar *s = N_("Change");
