#!/bin/sh

# [Gedit Tool]
# Name=Build
# Comment=Run "make" in the document directory
# Input=nothing
# Output=output-panel
# Shortcut=F8
# Applicability=local
##MimeType=
##Exec=fooview %F
##Icon=fooview.png
##Terminal= : wheter to show it in the bottom panel (default: true)
make
