#!/bin/sh

# [Gedit Tool]
# Name=Open Terminal Here
# Comment=Open a terminal in the document location
# Input=nothing
# Output=output-panel
# Shortcut=
# Applicability=local

#TODO: use "gconftool-2 -g /desktop/gnome/applications/terminal/exec"
gnome-terminal --working-directory=$GEDIT_CURRENT_DOCUMENT_DIR &
