#!/bin/sh

# [Gedit Tool]
# Name=Run Command
# Comment=Execute a custom command and put its output in a new document
# Input=nothing
# Output=new-document
# Shortcut=
# Applicability=all

#TODO: use "gconftool-2 -g /desktop/gnome/applications/terminal/exec"
exec `zenity --entry --title="Run command - gedit" --text="Command to run"`
