/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("gedit: Shell Output plugin");
gchar *s = N_("Specify the working directory and the command you want to run.");
gchar *s = N_("_Working directory:");
gchar *s = N_("Shell _command:");
gchar *s = N_("Select the working directory...");
