/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("gedit: Web Browse plugin");
gchar *s = N_("Enter the _URL to browse for:");
gchar *s = N_("Lynx found at: ");
gchar *s = N_("location");
gchar *s = N_(" _Change... ");
