/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("gedit web browse plugin");
gchar *s = N_("Enter the Url to browse for :");
gchar *s = N_("lynx was found at : ");
gchar *s = N_("location");
gchar *s = N_("Change");
